WebStatisMVC/Models/Articles.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace WebStatisMVC.Models
{
    public class Articles
    {
        [Key]
        public int id { get; set; }
        public string? Title { get; set; }
        [AllowHtml]
        public string? Description { get; set; }
        [StringLength(160, MinimumLength = 3)]
        public string? Excerpt { get; set; }
        [DataType(DataType.Date)]
        public DateTime? Publish_date { get; set; }
        public string? Author { get; set; }
        public int? Time_read { get; set; }

        public string? Category { get; set; }
        public string? Featured_images { get; set; }
    }
}

WebStatisMVC/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebStatisMVC.Data;
using WebStatisMVC.Models;

namespace WebStatisMVC.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly WebStatisMVCContext _context;

        private readonly IWebHostEnvironment _hostingEnvirontment;
        public ArticlesController( WebStatisMVCContext context, IWebHostEnvironment hostingEnvirontment)
        {
            _context = context;
            _hostingEnvirontment = hostingEnvirontment;
        }

        // GET: Articles
        public IActionResult Index()
        {
            /*return _context.Article != null ? 
                        View(await _context.Article.ToListAsync()) :
                        Problem("Entity set 'WebStatisMVCContext.Article'  is null.");*/
            var articles = _context.Articles.ToList();

            return View(articles);
        }

        public IActionResult AllBlog()
        {
            var articles = _context.Articles.ToList();

            return View(articles);
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Articles == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        public async Task<IActionResult> Full(int? id)
        {
            if (id == null || _context.Articles == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Articles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Title,Description,Excerpt,Publish_date,Author,Time_read,Category")] Articles article, IFormFile? Featured_images)
        {
            if (Featured_images != null)
            {
                string nameFile = Featured_images.FileName;
                string folderPath = Path.Combine(_hostingEnvirontment.WebRootPath, "images");
                string filePath = Path.Combine(folderPath, nameFile);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await Featured_images.CopyToAsync(stream);
                }

                article.Featured_images = nameFile;
            }
            if (ModelState.IsValid)
            {
                _context.Add(article);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Articles == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Title,Description,Excerpt,Publish_date,Author,Time_read,Category")] Articles article, IFormFile? Featured_images)
        {
            if (Featured_images != null)
            {
                string nameFile = Featured_images.FileName;
                string folderPath = Path.Combine(_hostingEnvirontment.WebRootPath, "images");
                string filePath = Path.Combine(folderPath, nameFile);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await Featured_images.CopyToAsync(stream);
                }

                article.Featured_images = nameFile;
            }
            if (id != article.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Articles == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Articles == null)
            {
                return Problem("Entity set 'WebStatisMVCContext.Article'  is null.");
            }
            var article = await _context.Articles.FindAsync(id);
            if (article != null)
            {
                _context.Articles.Remove(article);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleExists(int id)
        {
            return (_context.Articles?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

WebStatisMVC/Views/Articles/AllBlog.cshtml
@model IEnumerable<WebStatisMVC.Models.Articles>

@{
    ViewData["Title"] = "All Blog";
}


<style>
    aside {
        padding: 10px;
        margin: 0 10px 10px 10px;
        width: 400px;
        float: right;
        border: solid;
        border-width: 1px;
    }

    .aside > article {
        margin-bottom: 30px;
    }
    .allblog{
        width: 600px;
        border: solid;
        border-width: 1px;
        padding: 10px;
        margin-bottom: 30px;
    }



</style>

<body>
<section class="blog">
    <h2>ALL BLOG</h2>
        <aside>
            <h3 style="text-align:center">The Most Popular Blog</h3>
            <br />
            @foreach (var item in Model.Take(5))
            {
                <article class="row g-0">
                    <figure class="col-md-6">
                        <img src="~/images/@item.Featured_images" style="width:100%; max-height:150px; object-fit:cover" />
                    </figure>
                    <div style="margin-left:5%" class="col-md-5">
                        <h5>@item.Title</h5>
                        <p>
                            @item.Excerpt
                            <a asp-area="" asp-controller="Articles" asp-action="Full" asp-route-id="@item.id">More..</a>
                        </p>
                    </div>
                </article>
            }


            <a asp-area="" asp-controller="Articles" asp-action="AllBlog"><h5>Lihat blog lainnya</h5></a>
            <br />
            <h3 style="text-align:center">Trending Topic Now</h3>
            @foreach (var item in Model.Take(5))
            {
                <ul>
                    <li>
                        <h5><a href="#">#@item.Category</a></h5>
                    </li>
                </ul>
            }
            <br />

            <h3 style="text-align:center">Someone You Might Know</h3>
            @foreach (var item in Model.Take(3))
            {
                <section class="people">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <figure>
                                    <img style="width:75px; height:75px" src="~/images/wireframe.png" class="rounded-circle" />
                                </figure>
                            </div>
                            <div class="col-md-6">
                                <h5>@item.Author</h5>
                                <h6>bio author</h6>
                            </div>
                            <div class="col">
                                <button class="rounded-pill" style="color:blue; height:30px">Follow</button>
                            </div>
                        </div>
                    </div>
                </section>

            }

        </aside>

    @foreach (var item in Model)
    {
        <article class="allblog row g-0">
            <figure class="col-md-6">
                <img src="~/images/@item.Featured_images" style="width:100%; max-height:200px; object-fit:cover" />
            </figure>
            <div style="margin-left:5%" class="col-md-5">
                <h5>@item.Title</h5>
                <p>
                    @item.Excerpt 
                    <a asp-area="" asp-controller="Articles" asp-action="Full" asp-route-id="@item.id">More..</a>
                </p>
                <div class="row row-cols-2 text-muted">
                    <div class="col">
                            <strong>@item.Author</strong>
                    </div>
                    <div style="text-align:end" class="col">
                        @Html.DisplayFor(modelItem=> item.Publish_date)
                    </div>
                    <div class="col">
                        @item.Time_read minutes read
                    </div>
                </div>
                <br />
                <button class="rounded-pill">@item.Category</button>
            </div>
        </article>
    }
</section>
</body>

WebStatisMVC/Views/Articles/Create.cshtml
@model WebStatisMVC.Models.Articles

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Excerpt" class="control-label"></label>
                <input asp-for="Excerpt" class="form-control" />
                <span asp-validation-for="Excerpt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Featured_images" class="control-label"></label>
                <input type="file" asp-for="Featured_images" class="form-control" accept="image/*" />
                <span asp-validation-for="Featured_images" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publish_date" class="control-label"></label>
                <input asp-for="Publish_date" class="form-control" />
                <span asp-validation-for="Publish_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time_read" class="control-label"></label>
                <input asp-for="Time_read" class="form-control" />
                <span asp-validation-for="Time_read" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
	
    <script src="https://cdn.ckeditor.com/ckeditor5/37.1.0/classic/ckeditor.js"></script>
    
    <script>
        ClassicEditor
            .create( document.querySelector( '#Description' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>
}

WebStatisMVC/Views/Articles/Delete.cshtml
@model WebStatisMVC.Models.Articles

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.Raw(Model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Excerpt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Excerpt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publish_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publish_date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time_read)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time_read)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebStatisMVC/Views/Articles/Details.cshtml
@model WebStatisMVC.Models.Articles

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Article</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.Raw(Model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Excerpt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Excerpt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publish_date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publish_date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Featured_images)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/@Html.DisplayFor(model=> model.Featured_images)" style="width:50%; max-height:400px; object-fit:cover"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time_read)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time_read)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebStatisMVC/Views/Articles/Edit.cshtml
@model WebStatisMVC.Models.Articles

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Excerpt" class="control-label"></label>
                <input asp-for="Excerpt" class="form-control" />
                <span asp-validation-for="Excerpt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Featured_images" class="control-label"></label>
                <input type="file" asp-for="Featured_images" class="form-control" accept="image/*" />
                <span asp-validation-for="Featured_images" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publish_date" class="control-label"></label>
                <input asp-for="Publish_date" class="form-control" />
                <span asp-validation-for="Publish_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time_read" class="control-label"></label>
                <input asp-for="Time_read" class="form-control" />
                <span asp-validation-for="Time_read" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdn.ckeditor.com/ckeditor5/37.1.0/classic/ckeditor.js"></script>

    <script>
        ClassicEditor
            .create(document.querySelector('#Description'))
            .catch(error => {
                console.error(error);
            });
    </script>
}

WebStatisMVC/Views/Articles/Full.cshtml
@model WebStatisMVC.Models.Articles

@{
    ViewData["Title"] = "Full Article";
}

<section class="detail-article">

<h1 style="text-align:center">@Html.DisplayFor(model => model.Title)</h1>
    
<div>   
    <figure>
        <center>
            <img src="~/images/@Html.DisplayFor(model=> model.Featured_images)" style="width:50%; max-height:400px; object-fit:cover" />
        </center>
    </figure>
    <div class="text-muted">        
        <p><strong>Author: @Html.DisplayFor(model=> model.Author)</strong></p>
        <p>Time Read: @Html.DisplayFor(model=> model.Time_read) Minutes</p>
        <p>Published at: @Html.DisplayFor(model=> model.Publish_date) </p>
    </div>
    @Html.Raw(Model.Description)
    <hr />
    <button class="rounded-pill">@Html.DisplayFor(model => model.Category)</button>
</div>
</section>

WebStatisMVC/Views/Articles/Index.cshtml
@model IEnumerable<WebStatisMVC.Models.Articles>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<table id="myTable" class="table">
    <thead>
        <tr>            
            <th>Title</th>
            <th>Excerpt</th>
            <th>Publish date</th>
            <th>Author</th>
            <th>Time read</th>
            <th>Category</th>
            <th>Featured images</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>            
            <td>@item.Title</td>
            <td>@item.Excerpt</td>
            <td>@Html.DisplayFor(modelItem => item.Publish_date)</td>
            <td>@item.Author</td>
            <td>@item.Time_read</td>
            <td>@item.Category</td>
            <td><img src="~/images/@item.Featured_images" style="max-width:100px; max-height:100px" /></td>
            <td>
                <ul>
                    <li><a asp-action="Edit" asp-route-id="@item.id">Edit</a></li>
                    <li><a asp-action="Details" asp-route-id="@item.id">Details</a></li>
                    <li><a asp-action="Delete" asp-route-id="@item.id">Delete</a></li>
                    <li><a asp-action="Full" asp-route-id="@item.id">Article ver</a></li>
                </ul>                
            </td>
        </tr>
}
    </tbody>
</table>
@section scripts {
    <script src="~/js/datatable.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
}